### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [zoff99/MetalabDoorWidget#1]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by zoff99** [comment]
can you provide good screenshots to add?

**Comment by mondlicht-und-sterne** [comment]
What do you mean by good screenshots? I would take the same screenshots as you and you are the programmer at the source. You would then also have to enter them into your fastlane.

**Comment by mondlicht-und-sterne** [comment]
Since the issue dates back a long time - can you just close
the issue? Thank you, my initial Issie was also just information.
